Hide exercises in progress
jac-uk/apply pull request #505
Opened 2020-10-06 10:06 UTC by tomlovesgithub

2020-10-06 16:16 UTC, lloback requested changes
@tomlovesgithub  can you explain to me what the code is doing? What is the ticket number? I don't see any major change in the code.

2020-10-07 08:54 UTC, tomlovesgithub commented
> @tomlovesgithub can you explain to me what the code is doing? What is the ticket number? I don't see any major change in the code.

This is the request from Jeremy to comment out the 'Exercises in progress' section from the vacancy page https://judicial-appointments.slack.com/archives/CLV1P6D6J/p1601924140006800

2020-10-07 10:28 UTC, lloback commented
Ok, I can see now what it is doing. It is not a good practice to merge code into the repo without a ticket number. You will be here for a while and it is important that you can go back and check the reason for the change. I had to ask you, because it was not clear to me.
Did Jeremy created the ticket? If not, you can create yourself and add that information here.

2020-10-07 23:30 UTC, lloback approved these changes

2020-10-07 23:30 UTC, lloback commented on src/views/Vacancies.vue
> +        <!-- <div class="inProgressApplicationsList">
There is another way of doing this on VUE which I think it is cleaner:

`v-if="false"

It hides it completely from the DOM

2020-10-07 23:30 UTC, merged