Feature/491 save skip
jac-uk/apply pull request #506
Opened 2020-10-06 13:06 UTC by lloback

Fixed the SAVE & CONTINUE button when the user is coming from the PREVIEW page.
The rules that was there was only diverting to REVIEW after the user skipped all the questions.
This, fixes that.

2020-10-06 13:53 UTC, warrensearle requested changes

2020-10-06 13:53 UTC, warrensearle commented on src/views/QualifyingTests/QualifyingTest/Question.vue
> +      if (this.isLastQuestion || this.hasStartedAllQuestions || this.isComingFromReview) {
hmm, why does `hasStartedAllQuestions` not work sufficiently here? 
If it did then we wouldn't need the `isComingFromReview` variable

2020-10-06 14:22 UTC, lloback commented on src/views/QualifyingTests/QualifyingTest/Question.vue
> +      if (this.isLastQuestion || this.hasStartedAllQuestions || this.isComingFromReview) {
`hasStartedAllQuestions` is working but the code from `isComingFromReview` is neat.
I would keep both.

2020-10-06 14:22 UTC, lloback commented on src/views/QualifyingTests/QualifyingTest/Question.vue
> +      if (this.isLastQuestion || this.hasStartedAllQuestions || this.isComingFromReview) {
Let me know your thoughts

2020-10-07 22:23 UTC, warrensearle approved these changes
👍

2020-10-07 23:22 UTC, merged