#540 Add a browser info when the user logs in
jac-uk/apply pull request #626
Opened 2020-11-16 16:18 UTC by lloback

2020-11-17 23:38 UTC, warrensearle requested changes

2020-11-17 23:38 UTC, warrensearle commented on src/views/SignIn.vue
> +                email: userCredential.user.email,
I think probably we shouldn't capture email and display name here

2020-11-18 10:58 UTC, lloback commented on src/views/SignIn.vue
> +                email: userCredential.user.email,
This is done

2020-11-18 15:05 UTC, warrensearle approved these changes
👍

2020-11-18 16:06 UTC, merged