#625/remove vacancy-message
jac-uk/apply pull request #629
Opened 2020-11-17 13:54 UTC by tomlovesgithub

- Removed `vacancy-message.vue` and references in router. 
- Made links that would direct to that page just go through to `eligibilty-check.vue` (the citizenship question).
I think this covers everything needed to remove this and patch the journey.

There was no script of any kind in the vacancy message I'm sure just removing it will have no unintended side effects.

2020-11-17 23:40 UTC, warrensearle requested changes
Teeny tiny tweak

2020-11-17 23:40 UTC, warrensearle commented on src/router.js
> +// import VacancyMessage from '@/views/Vacancy/VacancyMessage';
Can remove this line rather than comment out

2020-11-18 08:59 UTC, warrensearle approved these changes
Looks good to me 👍

2020-11-18 09:23 UTC, merged

2020-11-18 10:13 UTC, tomlovesgithub commented on src/router.js
> +// import VacancyMessage from '@/views/Vacancy/VacancyMessage';
🤷‍♂️