Epic/563 changes to character section of application form
jac-uk/apply pull request #667
Opened 2020-12-15 08:36 UTC by mbrookeswebdev

2020-12-15 15:20 UTC, lloback approved these changes
I think this is good to go - but you should fix some bugs that I will post on the PR - please move them to a ticket.

2020-12-15 15:22 UTC, lloback commented
![image](https://user-images.githubusercontent.com/15261814/102234557-520fc780-3ee9-11eb-87e1-da7d856de3fe.png)

2020-12-15 15:25 UTC, lloback commented
![image](https://user-images.githubusercontent.com/15261814/102234994-c480a780-3ee9-11eb-8727-9a3d27a5b5f1.png)

2020-12-15 16:20 UTC, lloback commented
@mbrookeswebdev don't merge this yet.

2020-12-15 16:21 UTC, lloback requested changes
Don't merge this yet, because we need to coordinate this with the BA, other people. etc

2020-12-17 14:59 UTC, mbrookeswebdev commented on src/components/RepeatableFields/CharacterInformation/LateTaxReturnDetails.vue
> +      default: 'Please add details of your late tax return and provide details of any penalties or ' +
Done in ticket #668

2020-12-17 15:00 UTC, mbrookeswebdev commented on src/components/RepeatableFields/CharacterInformation/HmrcFineDetails.vue
> +      default: 'Please add details of the incident and provide details of any penalties or ' +
done in ticket #668

2020-12-17 15:01 UTC, mbrookeswebdev commented
I attached a hand in ticket #668

2021-01-06 14:25 UTC, lloback commented
Is this ready to go?

2021-01-06 14:25 UTC, lloback approved these changes

2021-01-06 14:30 UTC, mbrookeswebdev commented
Not quite, next week we will have a meeting and it is possible other changes will be requested.

2021-01-06 14:47 UTC, lloback commented
It is growing in size, and it is difficult to continue reviewing - 'agile' is small changes constantly and consistently!

2021-01-06 14:51 UTC, mbrookeswebdev commented
Agreed, I think it is a large epic!

2021-01-08 19:15 UTC, warrensearle reviewed
Added some comments for you

2021-01-09 20:25 UTC, lloback commented on src/helpers/constants.js
> +                      of my application.`;
it makes sense.

2021-01-11 17:27 UTC, warrensearle approved these changes
This is a good little piece of work :) 👍 
Let's get it tested.

2021-01-12 08:44 UTC, merged