limit word-input on ASC
jac-uk/apply pull request #705
Opened 2021-03-01 18:02 UTC by tomlovesgithub

2021-03-02 09:50 UTC, warrensearle reviewed
This looks good 👍 
Is this re-using the word limit implemented in QTs Scenario test? Or can Scenarios be updated so we share the same solution

2021-03-02 09:55 UTC, tomlovesgithub commented
This is a new solution, i wasn't sure if the QT solution would fit - defo worth comparing them

2021-03-02 11:12 UTC, warrensearle approved these changes
Approved. As discussed please consider combining with the word count in QT Scenarios so we avoid having duplicate code and it's easier to maintain

2021-03-02 11:13 UTC, mbrookeswebdev approved these changes

2021-03-02 14:58 UTC, HalcyonJAC commented
Hi @tomlovesgithub ,

First review here, hope I'm doing it right.
I've pulled down the branch and had a look at your work. It seems that it doesn't like it when you interact with the radio boxes. Once I select an answer it complains. Below there's a screenshot from the console.

<img width="653" alt="Screenshot 2021-03-02 at 14 39 16" src="https://user-images.githubusercontent.com/79906532/109664491-15a54c80-7b65-11eb-9d80-24763d2c7e3d.png">

2021-03-02 15:01 UTC, HalcyonJAC requested changes

2021-03-02 15:01 UTC, HalcyonJAC commented on src/components/Form/FormField.vue
> +          const words = this.value
`this.value` can be `null` and the code evaluates to `null.replace()..` which makes the console yell :(

2021-03-03 12:07 UTC, HalcyonJAC approved these changes

2021-03-03 12:08 UTC, merged