Split by non-alphabetic characters
jac-uk/apply pull request #707
Opened 2021-03-03 16:21 UTC by tomlovesgithub

An Addendum to the work on word limiting the ASC, we now split the string with all non-alphabetic characters as delimiters.
meaning 
`how.many3words!is_This?`
now registers as 5 words, not 1

2021-03-03 16:41 UTC, mbrookeswebdev approved these changes

2021-03-04 11:38 UTC, warrensearle requested changes

2021-03-04 11:38 UTC, warrensearle commented on src/components/Form/FormField.vue
> +            .split(/[^a-z]/i)
Please check whether you need `a-zA-Z` in your regex instead of just `a-z`

2021-03-04 11:47 UTC, warrensearle commented on src/components/Form/FormField.vue
> +            .split(/[^a-z]/i)
Sorry, ignore me. I missed the `/i` for case insensitive :)

2021-03-04 11:48 UTC, warrensearle approved these changes
👍

2021-03-04 13:53 UTC, HalcyonJAC approved these changes
Great job

2021-03-04 14:12 UTC, merged