allow 3 hyphens per word
jac-uk/apply pull request #709
Opened 2021-03-09 13:27 UTC by tomlovesgithub

Word count now allows 3 hyphens per word.
counts every 4th as the start of a new word
'so-no-more-cheating/-can-happen'

[Added some stuff from the GDS suggestions too
](https://design-system.service.gov.uk/components/character-count/)

2021-03-09 14:58 UTC, HalcyonJAC commented
Hi @tomlovesgithub 

The regex doesn't work well if the words have numbers in them...

...but I am not should whether the system needs to hande this type of input or not...

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/df216a78-7ac6-430b-8f37-c2008d3b7d81)

2021-03-09 15:04 UTC, HalcyonJAC commented
Hi @tomlovesgithub 

I think I have found the smallest bug in the world:

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/d9aaf0de-f53d-4016-ad24-e90a8adcba16)

....should say '1 word' instead of '1 words'

2021-03-09 22:54 UTC, warrensearle requested changes

2021-03-09 22:54 UTC, warrensearle commented on src/components/Form/TextareaInput.vue
> +      </span>
Could you simplify this with a computed which returns the `wordLimitMessage`?
(don't like seeing so much javascript inline in the template code)

2021-03-15 23:12 UTC, warrensearle commented
@tomlovesgithub CircleCI is reporting that four of the word count tests are failing. When I run the tests locally I get the same 4 failing tests. Are you able to fix the tests?

2021-03-16 16:39 UTC, mbrookeswebdev approved these changes

2021-03-16 22:21 UTC, warrensearle approved these changes
👍

2021-03-16 22:22 UTC, merged