Modal is fullscreen on mobiles
jac-uk/apply pull request #724
Opened 2021-03-17 18:28 UTC by tomlovesgithub

Scss changes to match prototype designs

2021-03-22 12:42 UTC, warrensearle requested changes
Have suggested a simplification of the css rules being used.
That said have successfully tested (with both ways of writing the rules) on the following browsers:
- ✅ Mac Chrome
- ✅ Mac Firefox
- ✅ Mac Safari

This will need testing on PC too (sorry can't help here as my virtualbox is out of action right now)

2021-03-22 12:42 UTC, warrensearle commented on src/components/Page/Modal.vue
> +  }
My preference would be to have the mobile overrides after the default style(s) say like this:
```
.modal {
    position: fixed;
    top: 50%;
    left: 50%;
    width: 30%;
    transform: translate(-50%, -50%);
    border: solid 2px #b1b4b6;
    background-color: #ffffff;
    @include mobile-view { 
      width: 100%;
      min-height: 100%;
    }
  }
```
Then you can also use `width` rather than introducing `min-width`

2021-03-23 15:09 UTC, HalcyonJAC approved these changes
Looks good to me :)

![image](https://user-images.githubusercontent.com/79906532/112169085-c85b4e80-8be9-11eb-8632-30d769d633fd.png)

2021-03-23 15:40 UTC, warrensearle approved these changes
Looks good 👍

2021-03-23 15:47 UTC, merged