#720 Added a message if vacancy was unpublished
jac-uk/apply pull request #732
Opened 2021-03-23 14:19 UTC by mbrookeswebdev

2021-03-24 09:12 UTC, mbrookeswebdev commented
To test - apply for an exercise, unpublish this exercise on Admin, log into Apply and check Applications tab for a message displaying under the unpublished exercise heading.

![Unpublish](https://user-images.githubusercontent.com/40855898/112284198-e32cd200-8c80-11eb-9d39-9d40bb8bb924.png)
![Data](https://user-images.githubusercontent.com/40855898/112284202-e58f2c00-8c80-11eb-9143-bdc5d4934a49.png)

2021-04-07 08:05 UTC, warrensearle requested changes
Hey @mbrookeswebdev when I look at my list of previous applications most of them now have the 'Data is temporarily unavailable' message. See below:
<img width="553" alt="Screenshot 2021-04-07 at 08 57 47" src="https://user-images.githubusercontent.com/8524401/113831708-cebbff80-977f-11eb-964b-453c9ce38bee.png">

Looking at the data for exercise 225 it appears to be approved & published just has now closed:
<img width="1202" alt="Screenshot 2021-04-07 at 09 02 23" src="https://user-images.githubusercontent.com/8524401/113832012-1b073f80-9780-11eb-8564-7c7673e4c650.png">

I would expect to still be able to view my previous application

2021-04-08 12:23 UTC, mbrookeswebdev commented
@warrensearle The 'vacancies/bind' call made in App.vue on line 115 over-writes the value of records in the vacancies store. I am not quite sure how to overcome that, any ideas?

2021-04-13 14:22 UTC, tomlovesgithub commented on src/store/vacancies.js
> +      unbindFirestoreRef('records');
My only issue is that i might ask for a note somewhere just to justify this nuance in phrasing. 
I understand the necessity but it might be quite confusing to stumble upon in a few months.

2021-04-13 14:24 UTC, tomlovesgithub approved these changes

2021-04-13 14:24 UTC, tomlovesgithub commented on tests/unit/store/vacancies.spec.js
>        records: [],
🎆Yey for tests!

2021-04-26 09:18 UTC, warrensearle approved these changes

2021-04-26 17:26 UTC, tomlovesgithub approved these changes

2021-05-04 14:51 UTC, KateMJAC approved these changes

2021-05-11 09:31 UTC, merged