Rollback 706/word-count changes
jac-uk/apply pull request #737
Opened 2021-04-06 13:43 UTC by tomlovesgithub

2021-04-06 15:17 UTC, warrensearle requested changes

2021-04-06 15:17 UTC, warrensearle commented on src/components/Form/FormField.vue
> +  <script>
These spaces seem to have crept in

2021-04-06 16:07 UTC, mbrookeswebdev requested changes
I agree with Warren, a couple of spaces, otherwise seems fine.

2021-04-07 12:10 UTC, mbrookeswebdev approved these changes
Looks good.

2021-04-07 12:24 UTC, merged