Remove name-blind sift and phone assessment from timeline
jac-uk/apply pull request #753
Opened 2021-04-16 15:24 UTC by tomlovesgithub

Removed timeline items
---
## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Visit an exercise you know has a name-blind sift and phone assessment on admin ([example](http://admin-develop.judicialappointments.digital/exercises/ZFF4xU8zNvneljZ8Ynsm/timeline))
- Visit the [corresponding vacancy page on apply](http://apply-develop.judicialappointments.digital/vacancy/ZFF4xU8zNvneljZ8Ynsm/)
- Ensure name-blind sift and Telephone assessment don't show on timeline

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

2021-04-21 08:29 UTC, mbrookeswebdev requested changes
Joy confirmed on the ticket the specific requirements, so this works as intended. Maybe just remove unwanted code rather than uncomment it.

2021-04-21 14:37 UTC, mbrookeswebdev approved these changes

2021-04-22 14:02 UTC, HalcyonJAC commented
Hi. The code in the Vue component has been commented out but the code for the unit test has been deleted. I think that either both should be commented our or both deleted...

2021-04-22 14:03 UTC, HalcyonJAC requested changes
Hi. The code in the Vue component has been commented out but the code for the unit test has been deleted. I think that either both should be commented our or both deleted...

2021-04-23 08:52 UTC, mbrookeswebdev approved these changes

2021-04-26 09:11 UTC, warrensearle requested changes
@tomlovesgithub I wonder if we could use the same timeline code in Apply and Admin, just ensure that it checks for data existence before displaying timeline events. (would mean we can move it to JAC Kit)
That way the logic for what shows on Apply vs Admin will be controlled in one place (in digital-platform where we decide which data to publish to Vacancies).

2021-04-26 09:11 UTC, warrensearle commented on src/helpers/Timeline/exerciseTimeline.js
>      if (data.shortlistingMethods.includes('situational-judgement-qualifying-test')) {
@tomlovesgithub I wonder if we could use the same timeline code in Apply and Admin, just ensure that it checks for data existence before displaying timeline events. (would mean we can move it to JAC Kit)
That way the logic for what shows on Apply vs Admin will be controlled in one place (in digital-platform where we decide which data to publish to Vacancies).

2021-04-26 16:09 UTC, tomlovesgithub commented on src/helpers/Timeline/exerciseTimeline.js
>      if (data.shortlistingMethods.includes('situational-judgement-qualifying-test')) {
yes please! a lot of the 'application enhancement' tickets would benefit from this change.

2021-05-13 14:35 UTC, tomlovesgithub commented on src/helpers/Timeline/exerciseTimeline.js
>      if (data.shortlistingMethods.includes('situational-judgement-qualifying-test')) {
There are complications with this however, for example, this ticket where name-blind and telephone assessments are hidden from candidates but show to admins

2021-05-13 16:18 UTC, tomlovesgithub commented
I'm very supportive of the idea of moving the timeline to JACKIT however i think we should make a separate issue for that as there are some discrepancies in the code and hurdles in terms displaying certain info for admins/applicants.

2021-05-13 16:18 UTC, tomlovesgithub commented
I'm very supportive of the idea of moving the timeline to JACKIT however i think we should make a separate issue for that as there are some discrepancies in the code and hurdles in terms displaying certain info for admins/applicants.

2021-05-14 13:04 UTC, KateMJAC reviewed
Tested with a positive result. 

This has been sent to UTG. Once I receive feedback, I will update.

2021-05-17 20:37 UTC, lloback approved these changes
This looks ok. Checked on browser

2021-05-20 09:00 UTC, HalcyonJAC approved these changes
Looks good to me now :)

2021-05-20 12:46 UTC, KateMJAC approved these changes
Positive user testing result.

2021-05-20 15:13 UTC, warrensearle approved these changes

2021-05-20 15:13 UTC, merged

2022-08-22 14:10 UTC, andrew-isaac commented
Reopened ticket as there is some issues with this and what a user and candidate experience!

As a user running an exercise around 95% of paper sift exercises are name blind - This is only a few where this is not the case. When a user sets up an exercise they select the "Name Blind Sift" option and input their dates onto a timeline.

The correct order for the timeline of events for a name blind paper sift is:

- Open for applications

- Close for applications

- JAC contacts IAs

- Return date for IAs

- Name blind sift

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/a0c33d5e-1096-47b7-84a6-dc107b9dd16a)

When this is displayed on the apply side to a candidate it is displayed in the incorrect order with the Name Blind Sift date missing. The list should follow the same order as above and where it has "Name Blind Sift" it should display the month and year for the candidate

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/b733d538-2487-4131-9be0-ea067bba0609)
o