Apply/517 qt analytics - save History and session time
jac-uk/apply pull request #774
Opened 2021-05-06 09:25 UTC by lloback

## What's included?
On this ticket we are adding History and Session time to the database. This will be stored and showed on the admin side.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
There are no changes to test on the apply as this is a backend ticket - we are just storgin information from the user, without any visual interface or interaction.
This needs to be tested in conjunction with the #945 ticket (admin).

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

2021-05-10 08:06 UTC, warrensearle requested changes

2021-05-10 08:06 UTC, warrensearle commented on src/views/QualifyingTests/QualifyingTest/Question.vue
> +      this.saveQuestionSession();
@lloback how tricky would it be to send data to firestore in one go rather than making, in this case, 3 separate calls (save history, save session and save response)? With a large QT this could mean higher costs for writing data plus there may be issues with making simultaneous calls to the same document.

2021-05-10 08:48 UTC, warrensearle commented on src/views/QualifyingTests/QualifyingTest/Question.vue
> +    this.questionSessionStart = firebase.firestore.Timestamp.fromDate(new Date());
There is an issue with this approach as it is effected by the time difference between client and server: start time is based upon local time; end time is based upon server time. (`end: firebase.firestore.FieldValue.serverTimestamp()`).
We should stay consistent and use one or the other. The preference would be to only use server time...OR to use local time but also record the offset from server time

2021-05-10 16:35 UTC, KateMJAC reviewed
This has been sent to UTG. An update will follow. 

It looks really exciting!!!!

2021-05-12 13:09 UTC, HalcyonJAC commented on src/views/QualifyingTests/QualifyingTest/Question.vue
> +      this.saveQuestionSession();
Hi,

Is it worth us reviewing this in light of the fact that this could be a major change?

2021-05-13 22:48 UTC, lloback commented on src/views/QualifyingTests/QualifyingTest/Question.vue
> +    this.questionSessionStart = firebase.firestore.Timestamp.fromDate(new Date());
Changed

2021-05-17 21:00 UTC, lloback commented on src/views/QualifyingTests/QualifyingTest/Question.vue
> +      this.saveQuestionSession();
One the main purposes of this task was to save data away from the normal flow of the SAVE. These functions are used on different parts, and the way that we are saving the ARRAYS are different from a simple UPDATE that is being used on the SAVE.

`await collection.doc(state.record.id).set(objToSave, { merge: true });`

This allows to add an item to the Array without the need to retrieve everything before saving.

2021-05-20 09:33 UTC, mbrookeswebdev approved these changes

2021-05-25 22:06 UTC, lloback commented on src/views/QualifyingTests/QualifyingTest/Question.vue
> +    this.questionSessionStart = firebase.firestore.Timestamp.fromDate(new Date());
I've addressed this specific issue @warrensearle

2021-05-25 22:07 UTC, lloback commented on src/views/QualifyingTests/QualifyingTest/Question.vue
> +      this.saveQuestionSession();
I've addressed this particular issue @warrensearle , as requested.

2021-05-25 22:07 UTC, lloback commented
This is ready for re-review.

2021-06-23 16:21 UTC, HalcyonJAC approved these changes

2021-06-30 09:28 UTC, warrensearle approved these changes

2021-06-30 10:51 UTC, KateMJAC commented
Please refer to #1317. Some final tweaks required to the tickets which run together.

2021-07-18 15:15 UTC, londonprojects commented
@warrensearle @londonprojects Can someone take a look at this?

2021-07-20 08:29 UTC, warrensearle commented
@lloback see https://github.com/jac-uk/admin/pull/1317 for changes to make

2021-07-30 12:02 UTC, lloback commented
Fix the "Saved"

"How many times changed answer:"
The `action: 'changed'` only works for Situational Judgement and Critical Analysis. Whenever the user clicks on an answer that is different from the previous selection, this count gets updated.

2021-08-05 15:02 UTC, tomlovesgithub approved these changes

2021-08-10 14:40 UTC, merged

2021-08-10 14:41 UTC, joy-ade commented
Approved by UTG