706 word limit
jac-uk/apply pull request #802
Opened 2021-07-06 16:28 UTC by tomlovesgithub

### sorting merge issues <img src='https://i.pinimg.com/originals/3d/83/ca/3d83cadee6b5ce8b6c32569f12304711.gif'/>

2021-07-07 10:27 UTC, mbrookeswebdev commented
@tomlovesgithub It looks like tests are failing + conflicts, could you have a look please.

2021-07-13 11:26 UTC, mbrookeswebdev commented
@tomlovesgithub I'm not sure how to test - I am looking at the Statement of Eligibility page and the component isn't there - 
https://jac-apply-develop--pr802-706-word-limit-hxh0325q.web.app/apply/KOpW1w2nCyVe83rVFlz6/statement-of-eligibility

2021-07-15 15:40 UTC, tomlovesgithub commented
> @tomlovesgithub I'm not sure how to test - I am looking at the Statement of Eligibility page and the component isn't there -
> https://jac-apply-develop--pr802-706-word-limit-hxh0325q.web.app/apply/KOpW1w2nCyVe83rVFlz6/statement-of-eligibility

It appears that ASC doesn't apply to that exercise, but it shouldn't be appearing in the list, ill need to investigate what the functionality should be based off warrens work.

2021-07-22 07:58 UTC, mbrookeswebdev commented
@tomlovesgithub It works well for me, would it be possible to extract this function into helpers somewhere to remove duplication?

2021-07-22 09:48 UTC, joy-ade reviewed
Out to UTG 22/7/2021 waiting for feedbacks

2021-07-22 10:31 UTC, warrensearle requested changes
Looks good, just a little bit of refactoring

2021-07-22 10:31 UTC, warrensearle commented on src/components/Form/TextareaInput.vue
> +      {{ wordLimit ? `In ${wordLimit} words, tell us how.` : null }}
I think this should be moved back out to the label prop rather than hard-coding a label here...
So in setting up a `Textareainput` to have word count you provide `wordLimit` prop to enable validation and `label` prop to include visual instruction to user.

2021-07-22 10:31 UTC, warrensearle commented on src/components/Form/FormField.vue
> +            this.setError('');
Agree with @mbrookeswebdev looks like this is duplicate code so would be good to just have one version to maintain. Could perhaps be a method in `FormField` or moved to a helper.

2021-07-22 10:31 UTC, warrensearle commented on src/components/Form/TextareaInput.vue
> +        })); // flatten array
See previous comment about duplicate code

2021-07-22 10:31 UTC, warrensearle commented on src/views/Apply/Assessments/SelfAssessmentCompetencies.vue
> +                  :word-limit="250"
Include the `label` here as well as `word-limit`

2021-07-22 14:02 UTC, mbrookeswebdev requested changes
I know that we discussed code duplication this morning, but as per Warren's comments duplicated code could be hard to maintain.

2021-07-22 15:00 UTC, joy-ade reviewed
Positive feedback from UTG

2021-07-26 09:42 UTC, warrensearle commented
Hey @tomlovesgithub can we discuss these changes (slack call), would just like to understand the `formData` changes and `labelHidden` prop. Thank you 😄

2021-07-27 09:17 UTC, HalcyonJAC commented
@tomlovesgithub @warrensearle Hey guys is this ready to review? Thanks!

2021-07-27 10:35 UTC, warrensearle requested changes

2021-07-27 10:35 UTC, warrensearle commented on src/components/Form/TextareaInput.vue
> +      aria-describedby="word-count-info"
It is my understanding that `aria-describedby` should reference an ID on the page. Is `word-count-info` an ID that exists on this page?

2021-07-27 11:15 UTC, warrensearle approved these changes
Looks great @tomlovesgithub 👍 
Bonus points if you add some unit tests for the FormField `words` method 😄

2021-07-28 00:57 UTC, HalcyonJAC approved these changes

2021-07-28 12:24 UTC, mbrookeswebdev approved these changes
👍

2021-08-03 08:55 UTC, merged