#1356 Fixes to QT timer
jac-uk/apply pull request #813
Opened 2021-07-29 12:11 UTC by warrensearle

**Author checklist**

- [x] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---

## What's included?
Fixes issues with the QT countdown timer.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

Test 1
Set your computer/tablet local time to X minutes in the future (e.g. 10:10 instead of 10:00)
Then open browser, navigate to apply site and start the test
Keep the test open and observe what happens, particularly X minutes before the expected end of the test
Is everything as expected?

Test 2
First set computer/tablet local time to X minutes in the past (e.g. 09:50:10 instead of 10:00)
Then open browser, navigate to apply site and start the test
Keep the test open and observe what happens
Is everything as expected?

Test 3
First open browser, navigate to apply site and start the test
Then set computer/tablet local time to X minutes in the future (e.g. 10:10 instead of 10:00)
Keep the test open and observe what happens
Is everything as expected?

Test 4
First open browser, navigate to apply site and start the test
Then set computer/tablet local time to X minutes in the past (e.g. 09:50 instead of 10:00)
Keep the test open and observe what happens
Is everything as expected?

Test 5 
Navigate to apply site and start the test 
Answer a question then exit the test 
Observe that the test is in the ‘Open tests’ list on the qualifying tests page 
Wait until the test has expired (e.g. for a 30 minute test wait more than 30 minutes) 
Is everything as expected? 
Is it possible to start the test again?

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2021-08-02 11:32 UTC, tomlovesgithub reviewed
Tested with all above local time settings. Works correctly in all circumstances.

2021-08-02 11:32 UTC, tomlovesgithub approved these changes

2021-08-03 09:06 UTC, warrensearle commented on tests/unit/views/QualifyingTests/QualifyingTests.spec.js
> +        expect(wrapper.find('h1.govuk-heading-l').text()).toBe('Future');
Thanks @tomlovesgithub I updated the units tests helper file to register the global filters

2021-08-04 14:23 UTC, HalcyonJAC approved these changes

2021-08-10 11:19 UTC, joy-ade commented
Out to UTG 09/08/2021 awaiting feedbacks

2021-08-16 15:09 UTC, mbrookeswebdev requested changes
@warrensearle I've tested Chrome and Safari, they behaved as expected, there was no issues in Safari when I navigated away from the test window. 

Unfortunately there were issues with Edge, I've had an error 'There is something wrong with test timer' in the 4 tests but it was possible to restart the test after clicking 'I understand' in the error modal and clicking on the test link again.

2021-08-19 16:41 UTC, mbrookeswebdev approved these changes
👍

2021-08-20 15:36 UTC, KateMJAC commented
Merging for Tuesday 24th Aug dry run on staging.

2021-08-20 15:36 UTC, merged