Prevent sign up with 'judicialappointments.gov.uk' emails
jac-uk/apply pull request #820
Opened 2021-11-26 16:00 UTC by tomlovesgithub

## What's included?
When an admin uses their gov.uk account to sign up as a candidate, it blocks them from signing in as an admin.
There are firebase configurations which would allow multiple accounts to be held under the same email address, but that presents additional issues.
Instead this code uses regex to match the email field and present a validation error when '@judicialappointments.gov.uk' is detected. 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Sign out.
- Go to sign up page
- type '[ANY]@judicialappointments.gov.uk'
- observe validation error

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2021-12-08 11:10 UTC, joy-ade commented
@tomlovesgithub I have just tested this ticket and the message displayed on my screen is different to the message in this. See the attachement for your reference ticket![Capture.PNG138.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/89043036-869d-44b5-864d-d688cac4e4fe)

2021-12-09 12:07 UTC, joy-ade reviewed
positive test by product team out to UTG 09/12/2021

2021-12-09 15:58 UTC, joy-ade approved these changes
Approved by UTG

2021-12-09 16:33 UTC, warrensearle approved these changes
👍

2021-12-10 15:35 UTC, joy-ade approved these changes
Approved by product team and UTG

2021-12-13 10:27 UTC, HalcyonJAC submitted a review, later dismissed

2021-12-13 10:27 UTC, HalcyonJAC commented on src/components/Form/FormField.vue
> +        JacEmail: /@judicialappointments.gov.uk\s*$/,
This `JacEmail` variable doesn't appear to be used anywhere.

Also, there is another `patternJACEmail` regex defined in the admin app which has the following value: `/@judicialappointments.(digital|gov.uk)$/` - i.e. it includes `.digital` extensions.

Perhaps the apply app should too?

2021-12-13 10:27 UTC, HalcyonJAC commented on src/views/SignUp.vue
> +  watch: {
When I try and enter `info@judicialappointments.gov.uk` as an email address it won't let me enter the last character. This watch block appears to be causing the problem.

Note that a validation error does not appear at all.

![image](https://user-images.githubusercontent.com/79906532/145795189-9d5af1e9-15f1-4c04-b458-7e1eb568edf1.png)

2021-12-22 15:10 UTC, warrensearle requested changes
Not sure about hard-coding a route into the `FormField` component... is there any way the validation here can be done in the sign up form instead? 

It'd be nice to use the same form field validation however alternatively this could be validated after the form is submitted and an error message displayed then, before the account is created.

Also right now the account is being created even if an error is displayed saying the email address ends with `@judicialappointments.gov.uk`. So it's not currently preventing sign up!

2021-12-22 15:14 UTC, warrensearle commented
@tomlovesgithub just checked and `FormField` has a `pattern` prop which accepts a regex and a message to be displayed if the regex fails:
<img width="157" alt="image" src="https://user-images.githubusercontent.com/8524401/147114141-68c21369-abb1-40bf-bcb4-3fdaa034347b.png">
This'd do the trick wouldn't?

2021-12-22 16:58 UTC, tomlovesgithub commented
> @tomlovesgithub just checked and `FormField` has a `pattern` prop which accepts a regex and a message to be displayed if the regex fails: <img alt="image" width="157" src="https://user-images.githubusercontent.com/8524401/147114141-68c21369-abb1-40bf-bcb4-3fdaa034347b.png"> This'd do the trick wouldn't it?

Oh nice!

2021-12-23 19:59 UTC, warrensearle approved these changes
Hey @tomlovesgithub looks like some code has been commented out. Otherwise all good.

2021-12-23 20:10 UTC, merged