667 - separating QT code
jac-uk/apply pull request #845
Opened 2022-01-10 16:49 UTC by HalcyonJAC

**Author checklist**

- [x] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [x] Fill in the details below and delete as appropriate
- [x] Be proactive in getting your work approved 💪

---

## What's included?
Hide the links to the Online Tests page but allow the page to be accessed directly still (via it's URL)

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Confirm that the Online Tests menu item cannot be seen anywhere in the application.
- Check that the /online-tests page can be accessed directly still

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

---
PREVIEW:DEVELOP

2022-01-18 11:51 UTC, HalcyonJAC commented on src/views/Applications.vue
> +                data-cy="vacancies-link"
Note: These `data-cy` attributes are to assist with Cypress testing

2022-01-25 09:20 UTC, warrensearle requested changes
@HalcyonJAC please fix broken tests

2022-01-31 18:32 UTC, warrensearle approved these changes

2022-02-03 12:01 UTC, tomlovesgithub commented on vue.config.js
> +    port: 8081,
Can this stay 8181?

2022-02-03 12:06 UTC, tomlovesgithub approved these changes

2022-02-03 12:40 UTC, HalcyonJAC commented
@warrensearle It seems that this file **src/views/QualifyingTests/QualifyingTest/Information.vue** which causes merge conflict will move to QT website after we separate QT code.

2022-02-03 15:50 UTC, HalcyonJAC commented on vue.config.js
> +    port: 8081,
I changed it just for consistency. With the this change port numbers allocated across each of the front-end platforms would be allocated as follows:

admin - 8080
apply - 8081
assessments - 8082
qt - 8083

2022-02-03 15:58 UTC, merged