Service offline page
jac-uk/apply pull request #872
Opened 2022-04-22 14:54 UTC by tomlovesgithub

## What's included?
Service offline page improved. 
GDS/JAC Styling used.
Advised wording added.

## Who should test?
✅ Product owner
✅ Developers

## How to test?

- Switch to branch locally 
- Open apply/service-offline/index.html with any browser

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context

![image](https://user-images.githubusercontent.com/44227249/164733770-975138ab-b7ca-4b77-a321-db8d4cbe08e4.png)

--- 

PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-04-26 09:08 UTC, HalcyonJAC approved these changes
Code looks great!

2022-04-26 09:26 UTC, warrensearle requested changes
Looks good, just a couple of niggles to tidy

2022-04-26 09:26 UTC, warrensearle commented on package.json
> +  "version": "1.53.2",
Please check 😄

2022-04-26 09:26 UTC, warrensearle commented on service-offline/index.html
> +                <br>
Indentation is a little off

2022-05-19 16:11 UTC, andrew-isaac commented
@tomlovesgithub  - Changes from comms team

![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/3813e7b6-fc72-4258-947a-7fb2fe5ec90c)

2022-05-31 12:55 UTC, andrew-isaac commented
@tomlovesgithub  - Can we have a new preview URL please? We would like to review this and push it out

2022-05-31 13:09 UTC, warrensearle approved these changes

2022-06-14 13:40 UTC, merged