showed html text in vacancies
jac-uk/apply pull request #892
Opened 2022-07-28 08:59 UTC by HalcyonJAC

## What's included?
Show HTML text (i.e., roleSummary, roleSummaryWelsh) on vacancies page.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Go to Vacancies and check role summary text format.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://user-images.githubusercontent.com/79906532/181465828-553e21e6-7a15-4fef-b99c-58edf52f5b29.mov

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-07-29 15:40 UTC, andrew-isaac approved these changes

2022-08-02 10:26 UTC, warrensearle requested changes
This is good however please consider amending the class name being used.
I'd suggest `custom-html` say so that all the places we are displaying html content would look like this:
```
<p 
  class="custom-html"
  v-html="htmlCode"
/>
```
Or for bonus points let's wrap it up in a component so it's like:
```
<CustomHTML value="htmlCode" />
```
That way all the styling fixes/overrides could be embedded within the component rather than adding them to the global CSS file.
This component would then be added to the `JAC-kit` so we can use it in all our apps.

2022-08-02 10:28 UTC, warrensearle requested changes
This is good however please consider amending the class name being used.
I'd suggest `custom-html` say so that all the places we are displaying html content would look like this:
```
<p 
  class="custom-html"
  v-html="htmlCode"
/>
```
rather than like this
```
<p 
  class="custom-ordered-list"
  v-html="htmlCode"
/>
```


---
Or for bonus points let's wrap it up in a component so it's like this:
```
<CustomHTML value="htmlCode" />
```
That way all the styling fixes/overrides could be embedded within the component rather than adding them to the global CSS file.

This component would then be added to the `JAC Kit` so we can use it in all our apps.

2022-08-02 11:35 UTC, tomlovesgithub approved these changes

2022-08-03 16:05 UTC, warrensearle approved these changes
Great work 👍

2022-08-03 16:21 UTC, tomlovesgithub approved these changes

2022-08-05 08:55 UTC, merged