Censor error message
jac-uk/apply pull request #904
Opened 2022-08-11 11:35 UTC by tomlovesgithub

## What's included?
If you try to log in with an email that doesnt exist, or if you use an incorrect password, you get the same error message, patching the security vulnerability presented by this issue.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Try to log in with a made up email that hasn't been registered to the site.
Try to log in with an email address which is registered but with an incorrect password.

Observe that both of the presented error messages are the same.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
![image](https://user-images.githubusercontent.com/44227249/184124652-4ccad7e1-19bd-4761-8a1b-cf4f2ec3ad7a.png)
---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-08-11 13:53 UTC, HalcyonJAC approved these changes

2022-08-12 08:17 UTC, warrensearle requested changes
Shouldn't we simply always return the same error message to the user?

2022-08-16 15:44 UTC, andrew-isaac reviewed
It works but I think the error message needs looking at - some examples below 

![image](https://user-images.githubusercontent.com/97609636/184922045-3fb05ac3-c05e-40ae-92b7-28aa1251a0e5.png)

![image](https://user-images.githubusercontent.com/97609636/184922101-dee9ec35-9ea5-4f7a-8963-409a956f9a9d.png)

2022-08-17 15:28 UTC, warrensearle approved these changes
👍

2022-09-07 15:43 UTC, andrew-isaac approved these changes

2022-10-05 23:59 UTC, merged