#926 Barrister eligibility
jac-uk/apply pull request #927
Opened 2022-10-04 16:35 UTC by HalcyonJAC

## What's included?
Describe the changes included in this pull request and highlight dependencies with other repos/tickets

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

---
PREVIEW:DEVELOP

2022-10-10 11:22 UTC, warrensearle approved these changes
Code change looks good to me 👍

2022-10-10 14:53 UTC, andrew-isaac approved these changes
Looks good - Can I ask does this information pull through to Panel Packs - If not I can write a new ticket

2022-10-11 12:02 UTC, HalcyonJAC commented
> Looks good - Can I ask does this information pull through to Panel Packs - If not I can write a new ticket

Hi @andrew-isaac, yes it will. I will implement it in this PR: [#926 Barrister eligibility](https://github.com/jac-uk/admin/pull/1745) in admin.

2022-11-02 12:23 UTC, tomlovesgithub requested changes
I might be misunderstanding, but please see my comment and let me know if ive misunderstood. 
Wouldn't want this to create chaos, perhaps we should migrate this field if we want to frame this question logically

2022-11-02 12:23 UTC, tomlovesgithub commented on src/components/RepeatableFields/Qualification.vue
> +      <RadioGroup
This will cause issues, not sure if it's my bad or an inherited legacy issue, but this question is posed as a negative, and the variable is defined as such, so this will cause issues with the display and comprehension of previous answers.

IE. the question has always been "i did not complete pupilage: true or false" so posing the question positively "have you completed pupilage: true or false" will invalidate all previous answers stored under this field 😅 - hope this makes sense.

2022-11-08 15:57 UTC, HalcyonJAC commented on src/components/RepeatableFields/Qualification.vue
> +      <RadioGroup
Use `qualificationComplete` instead of `qualificationNotComplete` to store if the pupillage has completed.

2022-12-08 16:23 UTC, tomlovesgithub approved these changes
Nice, tested in conjunction with the admin ticket, all working smooth!

2022-12-14 09:49 UTC, merged