#936 Refresh of Vacancy Page
jac-uk/apply pull request #939
Opened 2022-10-25 09:58 UTC by HalcyonJAC

## What's included?
A per Figma board a refresh of the vacancy list when a candidate is not signed into the platform - Slide 1-3

https://www.figma.com/proto/toOjVICtIYu5WmNbhJuyxm/JAC-Candidate-Profile?page-id=146%3A1970&node-id=1093%3A4988&viewport=-2547%2C1394%2C0.08&scaling=min-zoom&starting-point-node-id=1093%3A4988

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Go to vacancies and check if the UI meets the requirements.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP

2022-12-15 15:37 UTC, andrew-isaac approved these changes

2022-12-20 11:46 UTC, warrensearle requested changes
A few things to fix:

**Advert Type: Listing**
Should not have the Vacancy Details button. See the title no longer links to the details page, the button should use the same logic and be hidden for listing-only adverts
<img width="725" alt="image" src="https://user-images.githubusercontent.com/8524401/208642751-42d46e11-31f8-4912-8519-a217a9f69499.png">



**Advert type: Basic**
Launch date is shown twice:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/8524401/208644781-55eb532b-f3c9-43c4-be25-a208b8c7b2f3.png">

**Advert type: Basic**
Please check with @andrew-isaac the correct fields are displayed for Basic advert vs Full advert. The idea with the Basic advert is that minimal/essential information is shown whilst the team are pulling together the full information and then getting it approved. I suspect 'About the role' and 'Downloads' might be part of the content that needs approval before it is shown on the site.

**Back to top**
The side navigation links scroll smoothly - e.g. clicking 'About the role' smoothly scrolls to that content.
The back to top link does not scroll smoothly, the screen jumps straight to the top. This could be fine as is however your description suggests the intention is for smooth scrolling. So please double-check it's behaving as you expect 😄

2023-01-17 12:20 UTC, HalcyonJAC commented
@warrensearle I have checked with @andrew-isaac that `Relevant information (downloads)` will not show if the advert type is basic.

2023-01-19 14:28 UTC, warrensearle approved these changes
Looks good to me 👍

2023-01-26 10:08 UTC, tomlovesgithub approved these changes

2023-02-01 10:40 UTC, merged