#1763 Blank Draft Applications
jac-uk/apply pull request #950
Opened 2022-11-15 14:46 UTC by HalcyonJAC

## What's included?
When candidates apply for a vacancy, the platform will initialise the draft applications and pull the candidate information (e.g. full name and email address) from candidates collection in Firestone. It will make sure that there’re always full name and email in their draft applications.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
1. [apply] Apply for a vacancy without filling in any information.
2. [admin] Go to the draft application and check if there're values in the fields `Full name` and `Email address`.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP

2022-11-17 11:26 UTC, andrew-isaac approved these changes

2022-12-01 21:03 UTC, warrensearle requested changes
The call to `this.$store.getters['candidate/personalDetails']()` could return `null` therefore please check for it in lines 65-68. Otherwise all is good 😄

2022-12-08 11:56 UTC, tomlovesgithub approved these changes

2022-12-13 09:24 UTC, warrensearle approved these changes

2022-12-13 09:50 UTC, merged